### ISSUE TITLE
Adding docker support

### ISSUE THREAD

**Issue by elreydetoda** [wg-dashboard/wg-dashboard#11]
I just wanted to message and let this project know that it is possible to run wireguard in a docker container. If you checkout this project (sorry for linking a competitor in your github repo) https://github.com/subspacecloud/subspace#run-as-a-docker-container they show you what capabilities you have to add to run it, but it is possible.
The reason why adding it might be useful is modularity in environments. I heard about this project from the project chat for this [project](https://gitlab.com/NickBusey/HomelabOS), and they heavily use docker containers.
I just wanted to give you a heads up, but really cool project :smile:

**Comment by erdii** [comment]
We don't think that this is in scope for this project. The goal is to provide a simple onboarding and management experience and running wireguard inside a docker container needs it to be installed on the docker host itself (and to be loaded into the kernel). This:
* circumvents the whole "use docker as a 1-file 1-app setup vehicle" idea
* makes setup potentially opaque, because "why do i have to install something on my docker host? i already downloaded this image!"
