### ISSUE TITLE
More questions than issues...

### ISSUE THREAD

**Issue by cb3inco** [wg-dashboard/wg-dashboard#14]
I have more questions than issues. Thanks for your help in clarifying this.

1. Why is port 53 (DNS) opened on UFW for incoming traffic? If it's to connect to Cloudflare - that port default is 853? The reason I ask about this is because I've considered running WG on port 53 for some scenarios.
2. Does the CoreDNS stuff need to be enabled? If so, can I download the install script and remove that? If I would do that, what would break?
3. Any plans for IPv6 support? 
4. Any plans for accounts to have a little more restriction - ex. Help Desk person being able to create and delete peers but not change the server config? 
5. Plans to support additional WG interfaces wg1, wg2, etc.?

**Comment by cb3inco** [comment]
Also, how does one 'update'?

**Comment by erdii** [comment]
1. oh uh.... the DNS port should only be open on the wg0 interface! It is used for coredns so a secure dns can be provided over the vpn.
2. No you don't need to enable coredns. But then you have to ensure to use another dns server through the vpn tunnel to avoid dns leaks or other funky stuff. Also coredns uses DNS-over-TLS to encrypt the dns traffic between your server and Cloudflare.
3. No not currently. But we are open for PRs here :)
4. No because the dashboard is only reachable via ssh and letting an untrusted user connect to ssh has its whole own pack of security considerations that we didn't want to include in the project scope.
5. No not for now. What would be your intended use case here?
6. Updates. In theory you would download a new zipped release, backup the config, unzip into the existing installation, and copy back the config. Then restart wg-dashboard. But we could automate this in the future. PR welcome here, too :)

**Comment by heliostatic** [comment]
I took a stab at the updater with #22
