### ISSUE TITLE
Can't reach the panel

### ISSUE THREAD

**Issue by Ilo89** [wg-dashboard/wg-dashboard#39]
Hello someone know how to solve this problem ?

i open the 3000 port, but i f i go to my ip:3000 doesn't work 

Thank you

**Comment by erdii** [comment]
I think you missed step 1 in the setup manual:
For security reasons the dashboard only listens on localhost:3000, so you need to open an ssh tunnel from your computer to that specific port with: `ssh -L 3000:localhost:3000 <your_vps_user>@<your_vps_ip>`
Now you can access the dashboard from your computer via http://localhost:3000

**Comment by sbukiet** [comment]
@erdii 

I just followed your instructions but I still unable to connect to the server control panel. I the WG-Dashboard running as a ubunu server 18.04 and I'm on a different PC on the network trying to access the IP of the server.

**Comment by CrashElite104** [comment]
if you want it accessible from anyone `sudo ufw allow 3000` will allow http://<your_vps_ip>:3000 to be accessed from anywhere. you can also use `sudo ufw allow from X.X.X.X/32 to any port 3000` to allow only from one ip (or you could subnet it to allow a subnet).

**Comment by erdii** [comment]
Accessing the dashboard from anywhere via http is **highly** discouraged, as the  connection is not encrypted and private keys are sent to the client!

What we played around with was "making the dashboard accessible within the vpn itself, becuase the vpn ensures an encrypted connection" but we did not take this any further because could not convey it easily understandable to users.

**Comment by RawSlugs** [comment]
Why not set up https? (Can start with self signed cert and users can just replace the files with a cert from let's encrypt or whoever. - you can get let's encrypt certs via DNS validation, so you don't need to open ports etc.)
