### ISSUE TITLE
Could not save data: COULD_NOT_DISABLE_UFW_RULE when manual install

### ISSUE THREAD

**Issue by chemax** [wg-dashboard/wg-dashboard#40]
Manual installation without UFW (i'm doesnt need it), UFW checked as "option".
I'm try to configure server with web UI (change subnet, external ip).
```Optional: Enable ufw and forward port 22 and the desired port of the wireguard instance```
How i can fix it?

**Comment by linucksrox** [comment]
I installed from the script, and was having some other trouble. I decided to uninstall ufw since the instructions say it's optional, but then ran into this error because I guess the UI assumes ufw is installed and doesn't fail gracefully.
I guess the fix would be to install ufw, maybe you can just leave it disabled.
