### ISSUE TITLE
Downloaded config txt file using wrong DNS address

### ISSUE THREAD

**Issue by linucksrox** [wg-dashboard/wg-dashboard#44]
I updated and saved my configuration including changing the DNS IP address under server settings, then clicked Save and restart. Now when I create a peer and download the txt version of the config, it appears to be using the "Virtual Address" field from the server settings as the DNS entry for the interface instead of the expected "DNS" field.

**Comment by Zhmakda** [comment]
Confirm

Current config is
`  "virtual_ip_address": "192.168.99.254",
  "dns": "8.8.8.8",
`
But generated peer config has
`DNS = 192.168.99.254`

**Comment by erdii** [comment]
Hey @linucksrox  , sadly we recently decided to deprecate the project due to lack of time :(

---

**THIS PROJECT IS UNMAINTAINED**

If you want to take over development please contact us. In the meantime we recommend having a look at:

- https://github.com/tailscale/tailscale
- https://github.com/subspacecommunity/subspace
- https://github.com/EmbarkStudios/wg-ui

**Comment by linucksrox** [comment]
Oh, that's a bummer! But I appreciate you letting me know, and for posting links to other useful projects!
