### ISSUE TITLE
How to change coredns port from 53 to 1053

### ISSUE THREAD

**Issue by elohffa** [wg-dashboard/wg-dashboard#46]
Could u let me know how to edit the config file to change the coredns port from 53 to 1053

**Comment by daluf** [comment]
Currently (and in future too because we're removing CoreDNS) this is not possible through the dashboard. To change the CoreDNS Port you have to edit the coredns template (https://github.com/wg-dashboard/wg-dashboard/blob/master/src/views/templates/coredns_corefile.njk ) manually. Appending `:1053` after `{{ ip }}` should do the trick.

**Comment by elohffa** [comment]
Yes . I do the same hard code this in the template file
